### ISSUE TITLE
飲食店一覧機能

### ISSUE THREAD

**Issue by kengokonishi0824** [kengokonishi0824/Rese#4]
- [x]  テーブル作成migration
- [x]  案件シートを元にシーディング
- [ ]  viewとcontroller作成
- [x]  controller・・・テーブル情報取得

**Comment by kengokonishi0824** [comment]
migration, seeding・・・-11/11
controller・・・-11/12
view・・・-11/14

**Comment by gem-yours** [comment]
- [ ] カードの折返し
- [ ] 画像の表示
